name: Build

on: [push]
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  # WINDOWS x64 MSVC
  build-windows:
    name: Build-Windows-x64
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows x64 MSVC",
            os: windows-latest,
            artifact: "Windows-MSVC.tar.xz",
            build_type: "RelWithDebInfo",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            cc: "cl",
            cxx: "cl",
            archiver: "7z a",
            generators: "Visual Studio 16 2019"
          }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download submodules
        run: |
          git submodule update --init --recursive
          
      - name: Download submodule - GLM
        uses: Silverlan/common_actions/get_glm@actions
          
      - name: Download submodule - mathutil
        uses: Silverlan/common_actions/get_submodule@actions
        with:
          repo: 'https://github.com/Silverlan/mathutil.git'
          repo_name: 'mathutil'
          
      - name: CMake Build
        uses: Silverlan/common_actions/build_cmake@actions
        with:
          build_type: ${{ matrix.config.build_type }}
          build_generator: ${{ matrix.config.generators }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: upload-binary
          path: build/${{ matrix.config.build_type }}/sharedutils.lib
          
